# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: 'conan'
      image: 'conanio/gcc10:1.42.1'
      options: '--user 0:0'

stages:

- stage: 'build'
  displayName: 'Build Project'
  jobs:
  - job: 'build_x86_64'  
    container: 'conan'
    continueOnError: 'false'
    steps:
      - bash: scripts/helpers/conan-install.sh
        displayName: 'Installing all Conan dependencies'
        workingDirectory: $(Build.SourcesDirectory)

      - bash: |
          echo "Working directory is $(pwd)"
          scripts/build_x86-64.sh
          tar -zcf "build-x86_64.tar.gz" "build/" 
        displayName: 'Compile Code & Tests'
        workingDirectory: $(Build.SourcesDirectory)

      - publish: $(Buid.SourcesDirectory)/build-x86-64.tar.gz
        artifact: 'BuildFiles'

- stage: 'tests'
  displayName: 'Running Tests'
  jobs:
  - job:
    container: 'conan'
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Built Files'
        inputs:
          source: current
          artifact: 'BuildFiles'
          path: $(Build.SourcesDirectory)

      - bash: |
          tar -xzf "build-x86-64.tar.gz"
          cd 'build'
          echo "Build Directory: $(pwd)"
          ctest --verbose
        displayName: 'Running All Tests'
        workingDirectory: $(Build.SourcesDirectory)
