# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: 'conan'
      image: 'conanio/gcc10:1.42.1'
      options: '--user 0:0 --workdir /testing'

variables:
  - name: 'RootDir'
    value: '/base64azure/'

stages:

- stage: 'build'
  displayName: 'Build Project'
  jobs:
  - job: 'build_x86_64'  
    container: 'conan'
    continueOnError: 'false'
    steps:
      - checkout: self
        path: $(RootDir)
      - bash: scripts/helpers/conan-install.sh
        displayName: 'Installing all Conan dependencies'
        workingDirectory: $(RootDir)

      - bash: |
          echo "Working directory is $(pwd)"
          scripts/build_x86-64.sh
        displayName: 'Compile Code & Tests'
        workingDirectory: $(RootDir)

      - publish: $(RootDir)
        artifact: 'BuildFiles'

- stage: 'tests'
  displayName: 'Running Tests'
  jobs:
  - job:
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Built Files'
        inputs:
          source: current
          artifact: 'BuildFiles'
          path: $(RootDir)

      - bash: |
          cd 'build'
          echo "Build Directory: $(pwd)"
          ctest --verbose
        displayName: 'Running All Tests'
        workingDirectory: $(RootDir)
