# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: 'conan'
      image: 'conanio/gcc10:1.42.1'
      options: '--user 0:0'

stages:

- stage: 'failfast'
  displayName: 'Fail Fast Checks'
  jobs:
  - job: 'Build Project x86-64'  
    container: 'conan'
    continueOnError: 'false'
    steps:
      - bash: scripts/helpers/conan-install.sh
        displayName: 'Installing all Conan dependencies'

      - bash: scripts/build_x86-64.sh
        displayName: 'Compile Code & Tests'
